### PR TITLE
fix reconciliation of implementation resources when the network object is missing

### LINKED ISSUE #124: After deleting HTTPRoute, AuthorizationPolicy is still present
Current behaviour:
If you delete HTTPRoute and have bound AuthPolicy to it, it will still route those requests to the Authorino.

Expected behaviour:
On deletion of HTTPRoute, the AuthPolicy is also invalidated, and all resources created for it will disappear.

### LINKED ISSUE #127: AuthPolicy ApiKey allNamespace doesn't work
`AuthPolicy` like this won't work because the actual `AuthConfig` will be created in a different namespace (kuadrant-system) than the `AuthPolicy`.
```
spec:
  authScheme:
    identity:
      - apiKey:
          allNamespaces: false
          selector:
            matchLabels:
              group: testrun-phala-kudrnt-te-eskk-yelyse
        credentials:
          in: authorization_header
          keySelector: APIKEY
        metrics: false
        name: api_key
        priority: 0
```

### PR DESCRIPTION
**Pull request by guicassolato**
Fixes the reconciliation of internal (implementation) resources when the target network object is missing.

**Use-cases:**
1. clean-up upon deletion of the network object;
2. updates on the target network object referred by the policy;
3. updates on the spec (rules) of targeted network objects;
4. mismatching back references in the annotations.

**Approach:**<br/>
The main approach consists of working out the gateway diffs for a particular policy (i.e. gateways missing configuration, gateways already configured and gateways with stale configuration) and apply those diffs. When the target network object is present, it is straightforward; when on the other hand it cannot be found, the gateways otherwise affected are cleaned up.

**Main implementation resources targeted:**
* RateLimitPolicy
  - EnvoyFilter
  - WasmPlugin
* AuthPolicy
  - IstioAuthorizationPolicy

**Changes coming together in the package:**
- AuthConfigs created in the same namespace as their corresponding AuthPolicies (closes #127).

<br/>

Closes #124, (maybe) #125, #126, #127, #138, and who knows what many others... or maybe this doesn't fix anything at all and I could use a brain check.
### Verification steps

Follow the steps ❶ → ❻ and check the expected result after each step according the table below.

❶ Setup:
```sh
make local-setup

kubectl apply -f examples/toystore/toystore.yaml
kubectl apply -f examples/toystore/httproute.yaml

kubectl apply -f - <<EOF
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
spec: {}
EOF
```

❷ Create the policies:
```sh
kubectl apply -f - <<EOF
apiVersion: kuadrant.io/v1beta1
kind: AuthPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  authScheme: {}
---
apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: toystore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  rateLimits:
    - rules:
        - hosts: ["rate-limited.toystore.com"]
      configurations:
        - actions:
            - generic_key:
                descriptor_key: "limited"
                descriptor_value: "1"
      limits:
        - conditions:
            - "limited == 1"
          maxValue: 5
          seconds: 10
          variables: []
EOF
```

❸ Delete the HTTPRoute:
```sh
kubectl delete httproute/toystore
```

❹ Recreate the HTTPRoute now pointing to 2 Gateways:
```sh
kubectl apply -n istio-system -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kuadrant-ingressgateway
  labels:
    app: kuadrant
  annotations:
    kuadrant.io/namespace: default
spec:
  gatewayClassName: istio
  listeners:
    - name: default
      protocol: HTTP
      hostname: "*.kuadrant.io"
      port: 8080
      allowedRoutes:
        namespaces:
          from: All      
EOF
```
```sh
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: toystore
  labels:
    app: toystore
  annotations:
    kuadrant.io/ratelimitpolicy: 'default/toystore'
    kuadrant.io/authpolicy: 'default/toystore'
spec:
  parentRefs:
    - name: istio-ingressgateway
      namespace: istio-system
    - name: kuadrant-ingressgateway
      namespace: istio-system
  hostnames: ["*.toystore.com", "*.toystore.kuadrant.io"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/toy"
          method: GET
        - path:
            type: Exact
            value: "/admin/toy"
          method: POST
        - path:
            type: Exact
            value: "/admin/toy"
          method: DELETE
      backendRefs:
        - name: toystore
          port: 80
EOF
```

❺ Rollback the HTTPRoute to the originalk state of pointing to only 1 Gateway:
```sh
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: toystore
  labels:
    app: toystore
  annotations:
    kuadrant.io/ratelimitpolicy: 'default/toystore'
    kuadrant.io/authpolicy: 'default/toystore'
spec:
  parentRefs:
    - name: istio-ingressgateway
      namespace: istio-system
  hostnames: ["*.toystore.com"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/toy"
          method: GET
        - path:
            type: Exact
            value: "/admin/toy"
          method: POST
        - path:
            type: Exact
            value: "/admin/toy"
          method: DELETE
      backendRefs:
        - name: toystore
          port: 80
EOF
```

❻ Delete the policies
```sh
kubectl delete authpolicy/toystore
kubectl delete ratelimitpolicy/toystore
```

<br/>

**Expected results:**

<table>
  <thead>
    <tr>
      <th rowspan="2">Check</th>
      <th rowspan="2">Command</th>
      <th colspan="6">Expected result</th>
    </tr>
    <tr>
      <th>❶ Before creating the policies</th>
      <th>❷ After creating the policies</th>
      <th>❸ After deleting the HTTPRoute</th>
      <th>❹ After recreating the HTTPRoute pointing to 2 Gateways</th>
      <th>❺ After rolling back the HTTPRoute pointing to 1 Gateway</th>
      <th>❻ Deleting both policies</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>AuthPolicy status</td>
      <td><code>kubectl get authpolicy/toystore -o jsonpath='{.status}' | jq .</code></td>
      <td>Not found</td>
      <td>Ready / HTTPRoute protected</td>
      <td>ReconciliationError: HTTPRoute not found</td>
      <td>Ready / HTTPRoute protected</td>
      <td>Ready / HTTPRoute protected</td>
      <td>Not found</td>
    </tr>
    <tr>
      <td>Existing AuthConfigs</td>
      <td><code>kubectl get authconfig -A</code></td>
      <td>∅</td>
      <td>ap-default-toystore</td>
      <td>∅</td>
      <td>ap-default-toystore</td>
      <td>ap-default-toystore</td>
      <td>∅</td>
    </tr>
    <tr>
      <td>AuthConfig status</td>
      <td><code>kubectl get authconfig/ap-default-toystore -o jsonpath='{.status}' | jq .</code></td>
      <td>Not found</td>
      <td>Ready / 1 Host</td>
      <td>Not found</td>
      <td>Ready / 2 hosts</td>
      <td>Ready / 1 Host</td>
      <td>Not found</td>
    </tr>
    <tr>
      <td>Existing Istio AuthorizationPolicies</td>
      <td><code>kubectl get authorizationpolicy -A</code></td>
      <td>∅</td>
      <td>on-istio-ingressgateway-using-toystore</td>
      <td>∅</td>
      <td>on-istio-ingressgateway-using-toystore, on-kuadrant-ingressgateway-using-toystore</td>
      <td>on-istio-ingressgateway-using-toystore</td>
      <td>∅</td>
    </tr>
    <tr>
      <td>Istio AuthorizationPolicy specs and labels</td>
      <td><code>kubectl get authorizationpolicy/on-{istio|kuadrant}-ingressgateway-using-toystore -n istio-system -o yaml</code></td>
      <td>Not found</td>
      <td>
        <ul>
          <li>Labeled for the Gateway and AuthPolicy it's intended to</li>
          <li>Pointing to the <i>kuadrant-authorization</i></li>
          <li>Rules inherited from the HTTPRoute</li>
          <li>Workload selector matching the labels of the Gateway</li>
        </ul>
      </td>
      <td>Not found</td>
      <td>Same as ❷ for each AuthorizationPolicy</td>
      <td>Same as ❷</td>
      <td>Not found</td>
    </tr>
    <tr>
      <td>RateLimitPolicy status</td>
      <td><code>kubectl get ratelimitpolicy/toystore -o jsonpath='{.status}' | jq .</code></td>
      <td>Not found</td>
      <td>Ready / HTTPRoute protected</td>
      <td>ReconciliationError: HTTPRoute not found</td>
      <td>Ready / HTTPRoute protected</td>
      <td>Ready / HTTPRoute protected</td>
      <td>Not found</td>
    </tr>
    <tr>
      <td>Limitador CR spec</td>
      <td><code>kubectl get limitador/limitador -o jsonpath='{.spec}' | jq .</code></td>
      <td><code>{}<code></td>
      <td>Limits inherited from the HTTPRoute</td>
      <td><code>{}<code></td>
      <td>
        <ul>
          <li>Limits inherited from the HTTPRoute</li>
          <li>Rules repeated for every combination of Gateway x host</li>
        </ul>
      </td>
      <td>Limits inherited from the HTTPRoute</td>
      <td><code>{}<code></td>
    </tr>
    <tr>
      <td>Existing EnvoyFilters</td>
      <td><code>kubectl get envoyfilter -A | grep kuadrant</code></td>
      <td>∅</td>
      <td>kuadrant-ratelimiting-cluster-istio-ingressgateway</td>
      <td>∅</td>
      <td>kuadrant-ratelimiting-cluster-istio-ingressgateway, kuadrant-ratelimiting-cluster-kuadrant-ingressgateway</td>
      <td>kuadrant-ratelimiting-cluster-istio-ingressgateway</td>
      <td>∅</td>
    </tr>
    <tr>
      <td>EnvoyFilter specs and labels</td>
      <td><code>kubectl get envoyfilter/kuadrant-ratelimiting-cluster-{istio|kuadrant}-ingressgateway -n istio-system -o yaml</code></td>
      <td>Not found</td>
      <td>
        <ul>
          <li>Pointing to Limitador in the <code>default</code> namespace</li>
          <li>Workload selector matching the labels of the Gateway</li>
        </ul>
      </td>
      <td>Not found</td>
      <td>Same as ❷ for each EnvoyFilter</td>
      <td>Same as ❷</td>
      <td>Not found</td>
    </tr>
    <tr>
      <td>Existing WasmPlugins</td>
      <td><code>kubectl get wasmplugin -A</code></td>
      <td>∅</td>
      <td>kuadrant-istio-ingressgateway</td>
      <td>∅</td>
      <td>kuadrant-istio-ingressgateway, kuadrant-kuadrant-ingressgateway</td>
      <td>kuadrant-istio-ingressgateway</td>
      <td>∅</td>
    </tr>
    <tr>
      <td>WasmPlugin specs and labels</td>
      <td><code>kubectl get wasmplugin/kuadrant-{istio|kuadrant}-ingressgateway -n istio-system -o yaml</code></td>
      <td>Not found</td>
      <td>
        <ul>
          <li>Rules inherited from the HTTPRoute</li>
          <li>Pointing to the cluster configured by the corresponding EnvoyFilter</li>
          <li>Workload selector matching the labels of the Gateway</li>
        </ul>
      </td>
      <td>Not found</td>
      <td>Same as ❷ for each WasmPlugin</td>
      <td>Same as ❷</td>
      <td>Not found</td>
    </tr>
    <tr>
      <td>Gateway <code>istio-ingressgateway</code> annotations</td>
      <td><code>kubectl get gateway/istio-ingressgateway -n istio-system -o jsonpath='{.metadata.annotations}' | jq . | grep -v last-applied-configuration | grep kuadrant.io</code></td>
      <td><code>kuadrant.io/namespace: default</code></td>
      <td>Same as ❶ + <code>kuadrant.io/authpolicies</code> and <code>kuadrant.io/ratelimitpolicies</code> listing the policies</td>
      <td>Same as ❶ + <code>kuadrant.io/authpolicies</code> and <code>kuadrant.io/ratelimitpolicies</code> listing no policy</td>
      <td>Same as ❷</td>
      <td>Same as ❷</td>
      <td>Same as ❸</td>
    </tr>
    <tr>
      <td>Gateway <code>kuadrant-ingressgateway</code> annotations</td>
      <td><code>kubectl get gateway/kuadrant-ingressgateway -n istio-system -o jsonpath='{.metadata.annotations}' | jq . | grep -v last-applied-configuration | grep kuadrant.io</code></td>
      <td>Not found</td>
      <td>Not found</td>
      <td>Not found</td>
      <td><code>kuadrant.io/namespace: default</code> + <code>kuadrant.io/authpolicies</code> and <code>kuadrant.io/ratelimitpolicies</code> listing the policies</td>
      <td><code>kuadrant.io/namespace: default</code> + <code>kuadrant.io/authpolicies</code> and <code>kuadrant.io/ratelimitpolicies</code> listing no policy</td>
      <td>Same as ❺</td>
    </tr>
    <tr>
      <td>HTTPRoute annotations</td>
      <td><code>kubectl get httproute/toystore -o jsonpath='{.metadata.annotations}' | jq . | grep -v last-applied-configuration | grep kuadrant.io</code></td>
      <td>∅</td>
      <td><code>kuadrant.io/authpolicy</code> and <code>kuadrant.io/ratelimitpolicy</code> set to each corresponding policy</td>
      <td>Not found</td>
      <td>Same as ❷</td>
      <td>Same as ❷</td>
      <td>∅</td>
    </tr>
  </tbody>
</table>

### Test-cases not covered

- Policies targeting the Gateway
- Policies targeting the HTTPRoute and then deleting the Gateway
- Policies targeting the Gateway and then deleting the Gateway
- Alter the target ref in the policy

### Known issues

- Events on network resources missing the `kuadrant.io` annotation will not trigger the reconciliation of affected policies – e.g.
  - when re-applying the HTTPRoute (first pointing to 2 Gateways or later, when back to pointing to 1 Gateway), if we do not include the `kuadrant.io/{auth|ratelimit}policy` annotations;
  - when creating the 2nd Gateway, if we do not include the `kuadrant.io/namespace`.

### CODE REVIEW

File: controllers/ratelimitpolicy_controller.go [hunk 1]
```diff
@@ -82,39 +85,56 @@ func (r *RateLimitPolicyReconciler) Reconcile(eventCtx context.Context, req ctrl
...
 		}
 	}
 
-	specResult, specErr := r.reconcileSpec(ctx, rlp)
-	if specErr == nil && specResult.Requeue {
-		logger.V(1).Info("Reconciling spec not finished. Requeueing.")
-		return specResult, nil
-	}
+	// reconcile the ratelimitpolicy spec
+	specErr := r.reconcileResources(ctx, rlp, targetObj)
```
Comment (eguzki) [inline controllers/ratelimitpolicy_controller.go:134]: missing requeues. The reconcile Resources may want to requeue

**Review by eguzki — CHANGES_REQUESTED** [review]

**Comment by eguzki** [comment]
Verification steps failed to me. After deleting both policies, the authorizationpolicy was still there.

```
❯ kubectl get authorizationpolicy -A
NAMESPACE      NAME                                     AGE
istio-system   on-istio-ingressgateway-using-toystore   48s
```

File: controllers/ratelimitpolicy_controller.go (hunk 1 above)
Comment (guicassolato) [reply controllers/ratelimitpolicy_controller.go:134]: @eguzki ,

I think there was no case where the `reconcileResources` (previously `reconcileSpec`) returned `Requeue: true`, so the condition we had here before checking it was useless.

**Comment by guicassolato** [comment]
> Verification steps failed to me. After deleting both policies, the authorizationpolicy was still there.

@eguzki, did you follow all the steps and this happened after ❻ or you you deleted the policies arbitrarily at any other point?

Either way, the Istio AuthorizationPolicy should have been deleted of course. I'm just trying to redo your steps exactly, because I ran these steps as stated multiple steps and did not experience the same as you 🤔.

File: controllers/ratelimitpolicy_controller.go (hunk 1 above)
Comment (eguzki) [reply controllers/ratelimitpolicy_controller.go:134]: I do not know if there was a case, but even if there is none, the method allows requeuing, not just returning error. And I think it is useful for some uses cases. Maybe it was in the past, or will be in the future. The `kuadrant-controller` also has this capability.

File: controllers/authpolicy_auth_config.go [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+	existing, ok := existingObj.(*authorinoapi.AuthConfig)
+	if !ok {
+		return false, fmt.Errorf("%T is not an *authorinoapi.AuthConfig", existingObj)
+	}
+	desired, ok := desiredObj.(*authorinoapi.AuthConfig)
+	if !ok {
+		return false, fmt.Errorf("%T is not an *authorinoapi.AuthConfig", desiredObj)
+	}
+
+	existing.Spec = desired.Spec
```
[the remark this answers is not in the document]
Comment (guicassolato) [reply controllers/authpolicy_auth_config.go:134]: Done

File: controllers/authpolicy_istio_authorization_policy.go [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+	existing, ok := existingObj.(*istio.AuthorizationPolicy)
+	if !ok {
+		return false, fmt.Errorf("%T is not an *istio.AuthorizationPolicy", existingObj)
+	}
+	desired, ok := desiredObj.(*istio.AuthorizationPolicy)
+	if !ok {
+		return false, fmt.Errorf("%T is not an *istio.AuthorizationPolicy", desiredObj)
+	}
+
+	existing.Spec.Action = desired.Spec.Action
```
[the remark this answers is not in the document]
Comment (guicassolato) [reply controllers/authpolicy_istio_authorization_policy.go:193]: Done

File: controllers/authpolicy_auth_config.go [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+	if !ok {
+		return false, fmt.Errorf("%T is not an *authorinoapi.AuthConfig", existingObj)
+	}
+	desired, ok := desiredObj.(*authorinoapi.AuthConfig)
+	if !ok {
+		return false, fmt.Errorf("%T is not an *authorinoapi.AuthConfig", desiredObj)
+	}
+
+	if reflect.DeepEqual(existing.Spec, desired.Spec) && reflect.DeepEqual(existing.Annotations, desired.Annotations) {
+		return true, nil
```
Comment (eguzki) [inline controllers/authpolicy_auth_config.go:131]: it should return `false`

File: controllers/authpolicy_istio_authorization_policy.go [hunk 5]
```diff
@@ -185,6 +186,10 @@ func alwaysUpdateAuthPolicy(existingObj, desiredObj client.Object) (bool, error)
 		return false, fmt.Errorf("%T is not an *istio.AuthorizationPolicy", desiredObj)
 	}
 
+	if reflect.DeepEqual(existing.Spec, desired.Spec) && reflect.DeepEqual(existing.Annotations, desired.Annotations) {
+		return true, nil
```
Comment (eguzki) [inline controllers/authpolicy_istio_authorization_policy.go:190]: it should return `false`

File: controllers/authpolicy_auth_config.go (hunk 4 above)
Comment (guicassolato) [reply controllers/authpolicy_auth_config.go:131]: Oops.

Comment (guicassolato) [reply controllers/authpolicy_auth_config.go]: Fixed

File: controllers/authpolicy_istio_authorization_policy.go (hunk 5 above)
Comment (guicassolato) [reply controllers/authpolicy_istio_authorization_policy.go]: Fixed.

File: controllers/ratelimitpolicy_controller.go [hunk 6]
```diff
@@ -82,39 +85,56 @@ func (r *RateLimitPolicyReconciler) Reconcile(eventCtx context.Context, req ctrl
...
-		if err := r.finalizeRLP(ctx, rlp); err != nil {
-			return ctrl.Result{}, err
-		}
+	markedForDeletion := rlp.GetDeletionTimestamp() != nil
 
-		logger.Info("removing finalizer")
-		controllerutil.RemoveFinalizer(rlp, rateLimitPolicyFinalizer)
-		if err := r.UpdateResource(ctx, rlp); client.IgnoreNotFound(err) != nil {
+	// fetch the target network object
+	targetObj, err := r.FetchValidTargetRef(ctx, rlp.GetTargetRef(), rlp.Namespace)
```
Comment (didierofrivia) [inline controllers/ratelimitpolicy_controller.go:91]: Maybe we could be explicit here and name it `targetNetworkObj` or simply `networkObj` to avoid confusion further in the code with other _targets_ , wdyt?

File: controllers/authpolicy_status.go [hunk 7]
```diff
@@ -27,7 +27,7 @@ func (r *AuthPolicyReconciler) reconcileStatus(ctx context.Context, ap *kuadrant
 	if specErr == nil { // skip fetching authconfig if we already have a reconciliation error.
 		apKey := client.ObjectKeyFromObject(ap)
 		authConfigKey := client.ObjectKey{
-			Namespace: kuadrantNamespace,
+			Namespace: ap.Namespace,
```
Comment (didierofrivia) [inline controllers/authpolicy_status.go:30]: So I reckon it wasn't needed to place the AuthConfigs where Authorino would be (Kuadrant NS)... then there's no need to annotate the AuthPolicy nor get Kuadrant namespace which explains why the logic was removed and simplified :)

**Review by didierofrivia — COMMENTED** [review]
It's a great refactor, minor comment left.. Still need to do the steps.

**Review by didierofrivia — APPROVED** [review]
It works as described too! great job 🎖️
